#!/usr/bin/expect
set timeout 300
set done 0
spawn -ignore HUP android update sdk --no-ui --all --filter platform-tools,extra-android-support,tools,build-tools-24.0.3,android-24,android-19,extra,sys-img-armeabi-v7a-android-19
while {$done == 0} {
  expect {
    expect "Done*packages installed.*" {
      set done 1
    }
    expect "Do you accept*\[y/n\]*" {
      sleep 1
      send "y\r"
    }
  }
}
